### PR TITLE
jAuth: fix logout action

### PR DESCRIPTION
**Pull request by julieni**

### CODE REVIEW

**Comment by laurentj** [comment]
Could you explain what is the issue?

**Comment by laurentj** [comment]
Ah. I think I found: $rep->url is not filled in some case, right?

**Comment by julieni** [comment]
Hello, yes redirectUrl was not filled in some basic case, for exemple in the logout action from master_admin. Enabling $conf['enable_after_logout_override'] was mandatory for the redirect to work.

**Comment by xv4y** [comment]
Hi Julien, Laurent.

Ok, got the same problem here. Thanks for workaround. Looking forward to update to Jelix 1.6.6.

Thanks for your good work.

**Pull request merged**
